# This is a config for E2B sandbox template.
# You can use template ID (v4l1izrngjlba5qq5r5h) or template name (genie2-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("genie2-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("genie2-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('genie2-nextjs-test-2')

team_id = "5a8e8f93-adbf-4a72-ad99-1bc87e81540b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "genie2-nextjs-test-2"
template_id = "v4l1izrngjlba5qq5r5h"
